### ISSUE TITLE
PHP Parse syntax error ArrayUtils.php

### ISSUE THREAD

**Issue by rubentebogt** [webservices-nl/utils#1]
Beste Webservices,

Ik krijg de volgende error na een update van jullie terug;
```
PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /home/blabla/blabla/blabla/vendor/webservices-nl/utils/src/ArrayUtils.php on line 224

  [Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE)
```

Er staan inderdaad wat puntjes getypt voor een parameter op regel 224 en regel 241. Kunnen jullie hier eens naar kijken?

**Comment by rubentebogt** [comment]
@Bouwdie @kanariezwart @fraghi

**Comment by Bouwdie** [comment]
Hi Ruben, 

Thx voor je melding. Dit klopt inderdaad; dit is de slat operator, geïntroduceerd in PHP-5.6. De composer.json reflecteert dit nog niet hier staat nog ^5.4 en hoger (bug). Het upgraden van de php-versie naar ^5.6 gaat de syntax error voor je verhelpen. Wij zullen een fix maken waarbij de required php versie verhoogd wordt. Is een php-ugrade een mogelijkheid voor jullie software? 🥇

**Comment by rubentebogt** [comment]
@Bouwdie Aha, nog nooit van die operator gehoord, weer wat geleerd. We draaien jullie software momenteel op php 7 maar onze continues integration software blijft testen op mogelijke phpversies, de fout komt dus naar voren na een phpunit call op 5.5 denk ik, ik kan dit gewoon aanpassen natuurlijk dus ik weet even voldoende.

**Comment by Bouwdie** [comment]
@rubentebogt Goed om te horen dat jullie 7 draaien. Mooi dat dit probleem zo kan  worden opgelost kan worden. https://lornajane.net/posts/2014/php-5-6-and-the-splat-operator is een goede uitleg overigens.

**Comment by kanariezwart** [comment]
@rubentebogt we made a fix. Thanks for pointing that out.
Composer checks you to have php 5.6+. please checkout the [1.0.4 release](https://github.com/webservices-nl/utils/releases/tag/1.0.4)
